<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Gwarancjei usugi_icon-trash</name>
   <tag></tag>
   <elementGuidId>ccf51600-14f3-47c4-a5af-373f9d33f849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item-remove > i.icon-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='basket-main']/div[2]/div[2]/div/div[4]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-trash</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basket-main&quot;)/div[@class=&quot;order-box basket-box&quot;]/div[@class=&quot;basket-box-items&quot;]/div[@class=&quot;item-container productData item-active&quot;]/div[@class=&quot;item-remove&quot;]/i[@class=&quot;icon-trash&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basket-main']/div[2]/div[2]/div/div[4]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/i</value>
   </webElementXpaths>
</WebElementEntity>
