<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Komputery</name>
   <tag></tag>
   <elementGuidId>f2795f25-c4db-4f82-af4e-85d20c804bd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cn-departments-menu-item.cn-menu-item.cn-menu-item-hover.menu-komputery.has-submenu.show-menu > a.cn-departments-name.cn-link.cn-name > span.cn-name-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='common_navigation']/div[2]/div[2]/div/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cn-name-value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Komputery
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common_navigation&quot;)/div[@class=&quot;cn-window&quot;]/div[@class=&quot;cn-bar&quot;]/div[@class=&quot;cn-shop cn-current-frontend&quot;]/ul[@class=&quot;cn-current-departments cn-level&quot;]/li[@class=&quot;cn-departments-menu-item cn-menu-item cn-menu-item-hover menu-komputery has-submenu show-menu&quot;]/a[@class=&quot;cn-departments-name cn-link cn-name&quot;]/span[@class=&quot;cn-name-value&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='common_navigation']/div[2]/div[2]/div/ul/li[2]/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pozostałe akcesoria do laptopów'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akcesoria poleasingowe'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokaż wszystko w: Komputery'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
   </webElementXpaths>
</WebElementEntity>
